# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-23 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_membersuite_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersuiteportaluser',
            name='org_receives_member_benefits',
            field=models.BooleanField(default=False),
        ),
    ]
